language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: 7.0
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="3.0.*"

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS
